const KEY="bakerStreetProgress";
let save=JSON.parse(localStorage.getItem(KEY)||'{"unlocked":1,"total":0,"best":{}}');
let level=null,index=0,score=0,answered=false;
const app=document.querySelector("#app");
function persist(){localStorage.setItem(KEY,JSON.stringify(save))}
function shell(body){app.innerHTML='<header><div class="kicker">A Sherlock Holmes Trivia Game</div><h1>The Baker Street Academy</h1><div class="subtitle">Observe. Deduce. Prove your mastery of the Canon.</div></header>'+body+'<footer>Based on the Sherlock Holmes works of Sir Arthur Conan Doyle</footer>'}
function home(){let cards=LEVELS.map(l=>{let lock=l.id>save.unlocked,b=save.best[l.id];return '<article class="card '+(lock?'locked':'')+'" '+(!lock?'onclick="start('+l.id+')"':'')+'><div class="badge">'+(lock?'Locked':l.rank)+'</div><h2>Level '+l.id+'</h2><strong>'+l.title+'</strong><p>'+l.description+'</p><small>'+(b!=null?'Best: '+b+'%':'10 questions · '+l.points+' points each')+'</small></article>'}).join("");shell('<div class="stats"><span class="pill">Total points: '+save.total+'</span><span class="pill">Levels unlocked: '+save.unlocked+'/'+LEVELS.length+'</span></div><h2>Cases</h2><section class="level-grid">'+cards+'</section>')}
function start(id){level=LEVELS.find(x=>x.id===id);index=0;score=0;answered=false;render()}
function render(){let q=level.questions[index],pct=index/level.questions.length*100,body='<button class="secondary" onclick="home()">← Casebook</button><div class="progress"><div style="width:'+pct+'%"></div></div><div class="badge">'+level.title+' · Question '+(index+1)+' of '+level.questions.length+'</div><h2 class="question">'+q.q+'</h2>';
if(q.type==="mc"){body+='<div class="choices">'+q.options.map((x,i)=>'<button class="choice" onclick="choose('+i+',this)">'+x+'</button>').join("")+'</div>'}else{body+='<input id="answer" type="text" autocomplete="off" placeholder="Type your answer…" onkeydown="if(event.key===\'Enter\')submitText()"><button onclick="submitText()">Check answer</button>'}
body+='<div id="feedback"></div>';shell(body)}
function norm(s){return s.toLowerCase().replace(/[^a-z0-9 ]/g,"").replace(/\s+/g," ").trim()}
function choose(i,el){if(answered)return;answered=true;let q=level.questions[index],ok=i===q.answer;document.querySelectorAll(".choice")[q.answer].classList.add("correct");if(!ok)el.classList.add("wrong");finish(ok,q)}
function submitText(){if(answered)return;let q=level.questions[index],v=norm(document.querySelector("#answer").value);if(!v)return;answered=true;let ok=q.accept.some(a=>norm(a)===v);finish(ok,q)}
function finish(ok,q){if(ok)score+=level.points;let f=document.querySelector("#feedback");f.className="feedback "+(ok?"good":"bad");f.innerHTML="<strong>"+(ok?"Elementary.":"Not quite.")+"</strong><p>"+q.explanation+"</p><button onclick='next()'>"+(index===level.questions.length-1?"See results":"Next question →")+"</button>"}
function next(){index++;answered=false;if(index<level.questions.length)render();else results()}
function results(){let max=level.questions.length*level.points,pct=Math.round(score/max*100),passed=pct>=70;save.total+=score;save.best[level.id]=Math.max(save.best[level.id]||0,pct);if(passed&&level.id<LEVELS.length)save.unlocked=Math.max(save.unlocked,level.id+1);persist();shell('<div class="badge">Case complete</div><h2 class="question">'+(passed?'The evidence is conclusive.':'The case remains open.')+'</h2><p>You scored <strong>'+score+' / '+max+'</strong> points ('+pct+'%). '+(passed?'You passed the 70% threshold'+(level.id<LEVELS.length?' and unlocked the next case.':'.'):'Revisit the evidence and try again.')+'</p><div class="stats"><button onclick="start('+level.id+')">Replay level</button><button class="secondary" onclick="home()">Return to casebook</button></div>')}
home();