const KEY="bakerStreetProgressV2";
const legacy=JSON.parse(localStorage.getItem("bakerStreetProgress")||"null");
let save=JSON.parse(localStorage.getItem(KEY)||"null")||{best:{},unlocked:1};
if(legacy&&Object.keys(save.best).length===0){save.best=legacy.best||{};save.unlocked=Math.max(1,legacy.unlocked||1)}
let level=null,index=0,score=0,answered=false,hearts=3,streak=0,hints=0,earned=0;
const app=document.querySelector("#app");
function persist(){localStorage.setItem(KEY,JSON.stringify(save))}
function mastered(){return LEVELS.filter(l=>(save.best[l.id]||0)>=PASS_SCORE).length}
function rank(){let m=mastered();return [...RANKS].reverse().find(r=>m>=r.min).name}
function totalPoints(){return LEVELS.reduce((sum,l)=>sum+Math.round((save.best[l.id]||0)/100*l.questions.length*l.points),0)}
function maxPoints(){return LEVELS.reduce((sum,l)=>sum+l.questions.length*l.points,0)}
function recalcUnlocked(){let u=1;for(let i=1;i<=LEVELS.length;i++){if((save.best[i]||0)>=PASS_SCORE)u=i+1;else break}save.unlocked=Math.min(LEVELS.length,u);persist()}
function shell(body){app.innerHTML='<header><div class="kicker">A Sherlock Holmes Canon Trivia Game</div><h1>The Baker Street Academy</h1><div class="subtitle">Observe. Deduce. Prove your mastery of the Canon.</div></header>'+body+'<footer>Based on the Sherlock Holmes works of Sir Arthur Conan Doyle</footer>'}
function stars(id){let p=save.best[id]||0;return p===100?3:p>=90?2:p>=PASS_SCORE?1:0}
function levelCard(l){let lock=l.id>save.unlocked,b=save.best[l.id],passed=(b||0)>=PASS_SCORE;return '<article class="card '+(lock?'locked ':'')+(passed?'passed':'')+'" '+(!lock?'onclick="start('+l.id+')"':'')+'><div class="badge">'+(lock?'Locked':passed?'Solved':l.rank)+'</div><h3>Level '+l.id+'</h3><strong>'+l.title+'</strong><p>'+l.description+'</p><small>'+(b!=null?'Best: '+b+'% · ':'')+l.questions.length+' questions · '+l.points+' pts each</small></article>'}
function resetProgress(){if(!window.confirm("Start a new detective? This permanently clears all saved scores, stars, ranks, and unlocked levels on this device."))return;localStorage.removeItem(KEY);localStorage.removeItem("bakerStreetProgress");save={best:{},unlocked:1};level=null;home()}
function home(){recalcUnlocked();let arcs=[...new Set(LEVELS.map(l=>l.arc))];let sections=arcs.map(a=>{let ls=LEVELS.filter(l=>l.arc===a),done=ls.filter(l=>(save.best[l.id]||0)>=PASS_SCORE).length;return '<section class="arc"><div class="arc-head"><div><div class="badge">Arc '+a+'</div><h2>'+ls[0].arcTitle+'</h2></div><span>'+done+'/'+ls.length+' solved</span></div><div class="level-grid">'+ls.map(levelCard).join("")+'</div></section>'}).join("");shell('<div class="stats"><span class="pill">Rank: '+rank()+'</span><span class="pill">Solved: '+mastered()+'/'+LEVELS.length+'</span><span class="pill">Mastery points: '+totalPoints().toLocaleString()+' / '+maxPoints().toLocaleString()+'</span></div><div class="campaign-note"><strong>Progression:</strong> score '+PASS_SCORE+'% or better to solve a case and unlock the next. Your highest score on each level determines Canon mastery.</div>'+sections)}
function start(id){level=LEVELS.find(x=>x.id===id);index=0;score=0;answered=false;hearts=3;streak=0;hints=0;earned=0;render()}
function render(){let q=level.questions[index],pct=index/level.questions.length*100,body='<button class="secondary" onclick="home()">← Casebook</button><div class="progress"><div style="width:'+pct+'%"></div></div><div class="badge">Level '+level.id+' · '+level.title+' · Question '+(index+1)+' of '+level.questions.length+'</div><h2 class="question">'+q.q+'</h2>';
if(q.type==="mc"){body+='<div class="choices">'+q.options.map((x,i)=>'<button class="choice" onclick="choose('+i+',this)"><span class="choice-letter">'+String.fromCharCode(65+i)+'</span>'+x+'</button>').join("")+'</div>'}else{body+='<p class="prompt-note">Type the answer. Common equivalent forms are accepted.</p><input id="answer" type="text" autocomplete="off" placeholder="Type your answer…" onkeydown="if(event.key===\'Enter\')submitText()"><button onclick="submitText()">Check answer</button>'}
body+='<button id="hint" class="secondary" onclick="hint()">💡 Hint (−5 XP)</button><div id="feedback" aria-live="polite"></div>';shell(body)}
function norm(s){return String(s).toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9 ]/g,"").replace(/\b(the|a|an)\b/g," ").replace(/\s+/g," ").trim()}
function choose(i,el){if(answered)return;answered=true;let q=level.questions[index],ok=i===q.answer;document.querySelectorAll(".choice")[q.answer].classList.add("correct");if(!ok)el.classList.add("wrong");finish(ok,q)}
function submitText(){if(answered)return;let q=level.questions[index],field=document.querySelector("#answer"),v=norm(field.value);if(!v)return;answered=true;field.disabled=true;let ok=q.accept.some(a=>norm(a)===v);finish(ok,q)}
function hint(){if(answered||hints===index+1)return;hints=index+1;earned=Math.max(0,earned-5);let q=level.questions[index];if(q.type==="mc"){let wrong=[...document.querySelectorAll(".choice")].filter((b,i)=>i!==q.answer&&!b.disabled);wrong.slice(0,2).forEach(b=>{b.disabled=true;b.classList.add("eliminated")})}else{document.querySelector("#answer").placeholder="Starts with: "+q.accept[0].charAt(0).toUpperCase()}document.querySelector("#hint").disabled=true;document.querySelector("#hint").textContent="Hint used"}
function finish(ok,q){if(ok){score+=level.points;streak++;earned+=level.points+(streak>=3?5:0)}else{hearts--;streak=0;}let f=document.querySelector("#feedback");f.className="feedback "+(ok?"good":"bad");f.innerHTML="<strong>"+(ok?"Elementary. +"+level.points+" points!":"Not quite. −1 heart.")+"</strong><p>"+q.explanation+"</p><button onclick='next()'>"+(index===level.questions.length-1?"See results":"Next question →")+"</button>"}
function next(){if(hearts<=0){results(true);return}index++;answered=false;hints=0;if(index<level.questions.length)render();else results(false)}
function results(outOfHearts=false){let max=level.questions.length*level.points,pct=Math.round(score/max*100),passed=!outOfHearts&&pct>=PASS_SCORE,old=save.best[level.id]||0,newBest=pct>old;save.best[level.id]=Math.max(old,pct);if(passed&&level.id<LEVELS.length)save.unlocked=Math.max(save.unlocked,level.id+1);persist();shell('<div class="badge">'+(outOfHearts?'Out of hearts':'Case complete')+'</div><h2 class="question">'+(passed?'The evidence is conclusive.':'The case remains open.')+'</h2><p>You scored <strong>'+score+' / '+max+'</strong> points ('+pct+'%). '+(passed?'You met the '+PASS_SCORE+'% standard'+(level.id<LEVELS.length?' and can proceed to the next case.':'.'):'You need '+PASS_SCORE+'% to solve this case.')+'</p>'+(newBest?'<p><strong>New best score.</strong></p>':'')+'<p>✦ '+earned+' XP earned this attempt · '+stars(level.id)+' / 3 mastery stars</p><div class="stats"><button onclick="start('+level.id+')">Replay level</button><button class="secondary" onclick="home()">Return to casebook</button></div>')}
home();